package com.id.kas.pojo;

// Generated Mar 2, 2015 11:08:12 AM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblAuditLog generated by hbm2java
 */
@Entity
@Table(name = "TBL_AUDIT_LOG", schema = "TESTDB")
public class TblAuditLog implements java.io.Serializable {

	private TblAuditLogId id;
	private String action;
	private Date businessDate;
	private Date chgDate;
	private String keyId;
	private String propertyChange;
	private String tblName;

	public TblAuditLog() {
	}

	public TblAuditLog(TblAuditLogId id, Date businessDate, Date chgDate,
			String tblName) {
		this.id = id;
		this.businessDate = businessDate;
		this.chgDate = chgDate;
		this.tblName = tblName;
	}

	public TblAuditLog(TblAuditLogId id, String action, Date businessDate,
			Date chgDate, String keyId, String propertyChange, String tblName) {
		this.id = id;
		this.action = action;
		this.businessDate = businessDate;
		this.chgDate = chgDate;
		this.keyId = keyId;
		this.propertyChange = propertyChange;
		this.tblName = tblName;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "userId", column = @Column(name = "USER_ID", nullable = false, length = 10)),
			@AttributeOverride(name = "id", column = @Column(name = "ID", nullable = false, scale = 0)) })
	public TblAuditLogId getId() {
		return this.id;
	}

	public void setId(TblAuditLogId id) {
		this.id = id;
	}

	@Column(name = "ACTION", length = 100)
	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "BUSINESS_DATE", nullable = false, length = 7)
	public Date getBusinessDate() {
		return this.businessDate;
	}

	public void setBusinessDate(Date businessDate) {
		this.businessDate = businessDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CHG_DATE", nullable = false, length = 7)
	public Date getChgDate() {
		return this.chgDate;
	}

	public void setChgDate(Date chgDate) {
		this.chgDate = chgDate;
	}

	@Column(name = "KEY_ID", length = 100)
	public String getKeyId() {
		return this.keyId;
	}

	public void setKeyId(String keyId) {
		this.keyId = keyId;
	}

	@Column(name = "PROPERTY_CHANGE")
	public String getPropertyChange() {
		return this.propertyChange;
	}

	public void setPropertyChange(String propertyChange) {
		this.propertyChange = propertyChange;
	}

	@Column(name = "TBL_NAME", nullable = false, length = 100)
	public String getTblName() {
		return this.tblName;
	}

	public void setTblName(String tblName) {
		this.tblName = tblName;
	}

}
