package com.id.kas.pojo;

// Generated Mar 2, 2015 11:08:12 AM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblBarang generated by hbm2java
 */
@Entity
@Table(name = "TBL_BARANG", schema = "TESTDB")
public class TblBarang implements java.io.Serializable {

	private String idBarang;
	private String createBy;
	private Date createDate;
	private String updateBy;
	private Date updateDate;
	private BigDecimal versi;
	private BigDecimal hargaperolehan;
	private String havechild;
	private Long jumlah;
	private String kodeBarang;
	private String kelBarang;
	private String ketBarang;
	private String merk;
	private String nodokumen;
	private String serialnumber;
	private Date tglperolehan;
	private String typeBarang;

	public TblBarang() {
	}

	public TblBarang(String idBarang, String kodeBarang, String kelBarang) {
		this.idBarang = idBarang;
		this.kodeBarang = kodeBarang;
		this.kelBarang = kelBarang;
	}

	public TblBarang(String idBarang, String createBy, Date createDate,
			String updateBy, Date updateDate, BigDecimal versi,
			BigDecimal hargaperolehan, String havechild, Long jumlah,
			String kodeBarang, String kelBarang, String ketBarang, String merk,
			String nodokumen, String serialnumber, Date tglperolehan,
			String typeBarang) {
		this.idBarang = idBarang;
		this.createBy = createBy;
		this.createDate = createDate;
		this.updateBy = updateBy;
		this.updateDate = updateDate;
		this.versi = versi;
		this.hargaperolehan = hargaperolehan;
		this.havechild = havechild;
		this.jumlah = jumlah;
		this.kodeBarang = kodeBarang;
		this.kelBarang = kelBarang;
		this.ketBarang = ketBarang;
		this.merk = merk;
		this.nodokumen = nodokumen;
		this.serialnumber = serialnumber;
		this.tglperolehan = tglperolehan;
		this.typeBarang = typeBarang;
	}

	@Id
	@Column(name = "ID_BARANG", unique = true, nullable = false, length = 15)
	public String getIdBarang() {
		return this.idBarang;
	}

	public void setIdBarang(String idBarang) {
		this.idBarang = idBarang;
	}

	@Column(name = "CREATE_BY", length = 20)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATE_DATE", length = 7)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "UPDATE_BY", length = 20)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "UPDATE_DATE", length = 7)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "VERSI", scale = 0)
	public BigDecimal getVersi() {
		return this.versi;
	}

	public void setVersi(BigDecimal versi) {
		this.versi = versi;
	}

	@Column(name = "HARGAPEROLEHAN", precision = 12)
	public BigDecimal getHargaperolehan() {
		return this.hargaperolehan;
	}

	public void setHargaperolehan(BigDecimal hargaperolehan) {
		this.hargaperolehan = hargaperolehan;
	}

	@Column(name = "HAVECHILD", length = 1)
	public String getHavechild() {
		return this.havechild;
	}

	public void setHavechild(String havechild) {
		this.havechild = havechild;
	}

	@Column(name = "JUMLAH", precision = 10, scale = 0)
	public Long getJumlah() {
		return this.jumlah;
	}

	public void setJumlah(Long jumlah) {
		this.jumlah = jumlah;
	}

	@Column(name = "KODE_BARANG", nullable = false, length = 3)
	public String getKodeBarang() {
		return this.kodeBarang;
	}

	public void setKodeBarang(String kodeBarang) {
		this.kodeBarang = kodeBarang;
	}

	@Column(name = "KEL_BARANG", nullable = false, length = 20)
	public String getKelBarang() {
		return this.kelBarang;
	}

	public void setKelBarang(String kelBarang) {
		this.kelBarang = kelBarang;
	}

	@Column(name = "KET_BARANG", length = 100)
	public String getKetBarang() {
		return this.ketBarang;
	}

	public void setKetBarang(String ketBarang) {
		this.ketBarang = ketBarang;
	}

	@Column(name = "MERK", length = 30)
	public String getMerk() {
		return this.merk;
	}

	public void setMerk(String merk) {
		this.merk = merk;
	}

	@Column(name = "NODOKUMEN", length = 30)
	public String getNodokumen() {
		return this.nodokumen;
	}

	public void setNodokumen(String nodokumen) {
		this.nodokumen = nodokumen;
	}

	@Column(name = "SERIALNUMBER", length = 30)
	public String getSerialnumber() {
		return this.serialnumber;
	}

	public void setSerialnumber(String serialnumber) {
		this.serialnumber = serialnumber;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "TGLPEROLEHAN", length = 7)
	public Date getTglperolehan() {
		return this.tglperolehan;
	}

	public void setTglperolehan(Date tglperolehan) {
		this.tglperolehan = tglperolehan;
	}

	@Column(name = "TYPE_BARANG", length = 30)
	public String getTypeBarang() {
		return this.typeBarang;
	}

	public void setTypeBarang(String typeBarang) {
		this.typeBarang = typeBarang;
	}

}
