package com.id.kas.pojo;

// Generated Jan 21, 2013 10:52:40 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblCoaMaster generated by hbm2java
 */
@Entity
@Table(name = "TBL_COA_MASTER", schema = "TESTDB")
public class TblCoaMaster extends AuditTrail implements java.io.Serializable {

	private String noCoa;
	private String description;
	private int lvl;
	private String parentCoa;
	private String groups;

	public TblCoaMaster() {
	}

	public TblCoaMaster(String noCoa) {
		this.noCoa = noCoa;
	}

	public TblCoaMaster(String noCoa, String description, int lvl, String parentCoa, String groups) {
		this.noCoa = noCoa;
		this.description = description;
		this.lvl = lvl;
		this.parentCoa = parentCoa;
		this.groups = groups;
	}

	@Id
	@Column(name = "no_coa", nullable = false, length = 5)
	public String getNoCoa() {
		return this.noCoa;
	}

	public void setNoCoa(String noCoa) {
		this.noCoa = noCoa;
	}

	@Column(name = "description", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "lvl")
	public int getLvl() {
		return this.lvl;
	}

	public void setLvl(int lvl) {
		this.lvl = lvl;
	}

	@Column(name = "parent_coa", length = 5)
	public String getParentCoa() {
		return this.parentCoa;
	}

	public void setParentCoa(String parentCoa) {
		this.parentCoa = parentCoa;
	}

	@Column(name = "groups", length = 1)
	public String getGroups() {
		return this.groups;
	}

	public void setGroups(String groups) {
		this.groups = groups;
	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tblCoaMaster")
//	public Set<TblCoaMap> getTblCoaBranchs() {
//		return this.tblCoaBranchs;
//	}
//
//	public void setTblCoaBranchs(Set<TblCoaMap> tblCoaBranchs) {
//		this.tblCoaBranchs = tblCoaBranchs;
//	}

}
