package com.id.kas.pojo;

// Generated Jan 21, 2013 10:52:40 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblFlowHistArchieve generated by hbm2java
 */
@Entity
@Table(name = "tbl_flow_hist_archieve", schema = "TESTDB")
//@IdClass(TblFlowHistArchieveId.class)
public class TblFlowHistArchieve extends AuditTrail implements java.io.Serializable {

//	private TblFlowHistArchieveId key;
	private String executorUserId;
	private Date executionDate;
	private Date executionTime;
	private String statusCodeChgTo;
	private Date expireDate;
	private Date expireTime;
	private Date dateTask;
	private String catatan;
	private String flag;
	private String noKontrak;
	private String cif;
	private String customerName;
	private String branchCodeOri;
	private String productCode;
	
	private long id;
	private String accountNo;
	private String flowCode;
	private String branchCode;

	public TblFlowHistArchieve() {
	}

//	public TblFlowHistArchieve(TblFlowHistArchieveId id) {
//		this.key = id;
//	}

	public TblFlowHistArchieve(long id, String accountNo, String flowCode, String branchCode, String executorUserId, Date executionTime, String statusCodeChgTo, Date expireDate, Date expireTime, Date dateTask, String catatan, String flag, String noKontrak, String cif, String customerName, String branchCodeOri) {
		this.id = id;
		this.accountNo = accountNo;
		this.flowCode = flowCode;
		this.branchCode = branchCode;
		this.executorUserId = executorUserId;
		this.executionTime = executionTime;
		this.statusCodeChgTo = statusCodeChgTo;
		this.expireDate = expireDate;
		this.expireTime = expireTime;
		this.dateTask = dateTask;
		this.catatan = catatan;
		this.flag = flag;
		this.noKontrak = noKontrak;
		this.cif = cif;
		this.customerName = customerName;
		this.branchCodeOri = branchCodeOri;
	}

//	@EmbeddedId
//	@AttributeOverrides({ @AttributeOverride(name = "idFlowHist", column = @Column(name = "id_flow_hist", nullable = false)), @AttributeOverride(name = "accountNo", column = @Column(name = "account_no", nullable = false, length = 16)), @AttributeOverride(name = "flowCode", column = @Column(name = "flow_code", nullable = false, length = 100)), @AttributeOverride(name = "branchCode", column = @Column(name = "branch_code", nullable = false, length = 5)) })
//	public TblFlowHistArchieveId getKey() {
//		return this.key;
//	}
//
//	public void setKey(TblFlowHistArchieveId key) {
//		this.key = key;
//	}

	@Id
	@Column(name = "id_flow_hist", nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Id
	@Column(name = "account_no", nullable = false, length = 16)
	public String getAccountNo() {
		return this.accountNo;
	}

	public void setAccountNo(String accountNo) {
		this.accountNo = accountNo;
	}

	@Id
	@Column(name = "flow_code", nullable = false, length = 100)
	public String getFlowCode() {
		return this.flowCode;
	}

	public void setFlowCode(String flowCode) {
		this.flowCode = flowCode;
	}

	@Id
	@Column(name = "branch_code", nullable = false, length = 5)
	public String getBranchCode() {
		return this.branchCode;
	}

	public void setBranchCode(String branchCode) {
		this.branchCode = branchCode;
	}
	
	@Column(name = "executor_user_id", length = 10)
	public String getExecutorUserId() {
		return this.executorUserId;
	}

	public void setExecutorUserId(String executorUserId) {
		this.executorUserId = executorUserId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "execution_time", length = 13)
	public Date getExecutionTime() {
		return this.executionTime;
	}

	public void setExecutionTime(Date executionTime) {
		this.executionTime = executionTime;
	}

	@Column(name = "status_code_chg_to", length = 100)
	public String getStatusCodeChgTo() {
		return this.statusCodeChgTo;
	}

	public void setStatusCodeChgTo(String statusCodeChgTo) {
		this.statusCodeChgTo = statusCodeChgTo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "expire_date", length = 13)
	public Date getExpireDate() {
		return this.expireDate;
	}

	public void setExpireDate(Date expireDate) {
		this.expireDate = expireDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "expire_time", length = 29)
	public Date getExpireTime() {
		return this.expireTime;
	}

	public void setExpireTime(Date expireTime) {
		this.expireTime = expireTime;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_task", length = 13)
	public Date getDateTask() {
		return this.dateTask;
	}

	public void setDateTask(Date dateTask) {
		this.dateTask = dateTask;
	}

	@Column(name = "catatan", length = 500)
	public String getCatatan() {
		return this.catatan;
	}

	public void setCatatan(String catatan) {
		this.catatan = catatan;
	}

	@Column(name = "flag", length = 1)
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	@Column(name = "no_kontrak", length = 16)
	public String getNoKontrak() {
		return this.noKontrak;
	}

	public void setNoKontrak(String noKontrak) {
		this.noKontrak = noKontrak;
	}

	@Column(name = "cif", length = 10)
	public String getCif() {
		return this.cif;
	}

	public void setCif(String cif) {
		this.cif = cif;
	}

	@Column(name = "customer_name", length = 100)
	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	@Column(name = "branch_code_ori", length = 5)
	public String getBranchCodeOri() {
		return this.branchCodeOri;
	}

	public void setBranchCodeOri(String branchCodeOri) {
		this.branchCodeOri = branchCodeOri;
	}
	

	@Temporal(TemporalType.DATE)
	@Column(name = "execution_date", length = 13)
	public Date getExecutionDate() {
		return executionDate;
	}

	public void setExecutionDate(Date executionDate) {
		this.executionDate = executionDate;
	}

	@Column(name = "product_code", length = 2)
	public String getProductCode() {
		return productCode;
	}

	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}

}
