package com.id.kas.pojo;

// Generated Jan 21, 2013 10:52:40 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblJurnalTransaksi generated by hbm2java
 */
@Entity
@Table(name = "tbl_jurnal_transaksi", schema = "TESTDB")
public class TblJurnalTransaksi extends AuditTrail implements java.io.Serializable {
	
	private long idJurnalTransaksi;
	private long jurnalId;
	
	private String norek;
	private String noCoa;
	private BigDecimal amountD;
	private BigDecimal amountK;
	private Date tglPosting;
	private Date waktu;
	private Date tglTransaksi;
	private String keterangan;
	public TblJurnalTransaksi() {
	}

	public TblJurnalTransaksi(long idJurnalTransaksi, long jurnalId, String norek, String noCoa, BigDecimal amountD, BigDecimal amountK, Date tglTransaksi, Date tglPosting, Date waktu) {
		this.idJurnalTransaksi = idJurnalTransaksi;
		this.jurnalId = jurnalId;
		this.norek = norek;
		this.noCoa = noCoa;
		this.amountD = amountD;
		this.amountK = amountK;
		this.tglTransaksi = tglTransaksi;
		this.tglPosting = tglPosting;
		this.waktu = waktu;
	}

	@Column(name = "norek", nullable = false, length = 16)
	public String getNorek() {
		return this.norek;
	}

	public void setNorek(String norek) {
		this.norek = norek;
	}

	@Column(name = "no_coa", nullable = false, length = 16)
	public String getNoCoa() {
		return this.noCoa;
	}

	public void setNoCoa(String noCoa) {
		this.noCoa = noCoa;
	}

	@Column(name = "amount_d", precision = 20,scale=2)
	public BigDecimal getAmountD() {
		return this.amountD;
	}

	public void setAmountD(BigDecimal amountD) {
		this.amountD = amountD;
	}

	@Column(name = "amount_k", precision = 20,scale=2)
	public BigDecimal getAmountK() {
		return this.amountK;
	}

	public void setAmountK(BigDecimal amountK) {
		this.amountK = amountK;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "tgl_posting", length = 13)
	public Date getTglPosting() {
		return this.tglPosting;
	}

	public void setTglPosting(Date tglPosting) {
		this.tglPosting = tglPosting;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "waktu", length = 29)
	public Date getWaktu() {
		return this.waktu;
	}

	public void setWaktu(Date waktu) {
		this.waktu = waktu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "tgl_transaksi", length = 13)
	public Date getTglTransaksi() {
		return this.tglTransaksi;
	}

	public void setTglTransaksi(Date tglTransaksi) {
		this.tglTransaksi = tglTransaksi;
	}

	@Column(name = "keterangan", length = 200)
	public String getKeterangan() {
		return keterangan;
	}

	public void setKeterangan(String keterangan) {
		this.keterangan = keterangan;
	}

	@Id
	@Column(name = "id_jurnal_transaksi", nullable = false)
	public long getIdJurnalTransaksi() {
		return this.idJurnalTransaksi;
	}

	public void setIdJurnalTransaksi(long idJurnalTransaksi) {
		this.idJurnalTransaksi = idJurnalTransaksi;
	}

	@Id
	@Column(name = "jurnal_id", nullable = false)
	public long getJurnalId() {
		return this.jurnalId;
	}

	public void setJurnalId(long jurnalId) {
		this.jurnalId = jurnalId;
	}
	
}
