package com.id.kas.pojo;

// Generated Jan 21, 2013 10:52:40 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblJurnal generated by hbm2java
 */
@Entity
@Table(name = "tbl_jurnal", schema = "TESTDB")
public class TblJurnal  extends AuditTrail implements java.io.Serializable {

	private long jurnalId;
	private String kodeTransaksi;
	private String keterangan;
	private String authorized;
	private String authorizedBy;
//	private String createBy;
	private String branchCode;
	private Date authorizedDate;
	private String refId;
	private String reverse;
	private String respCode;
	private Date tglTransaksi;
	private Date tglPosting;
//	private Date createDate;
	private String mobileBranchCode;

	public TblJurnal() {
	}

	public TblJurnal(long jurnalId) {
		this.jurnalId = jurnalId;
	}


	public TblJurnal(long nextSequenceOfJurnalId, String transactionCode, Date tglTransaksi,Date tglPosting) {
		this.jurnalId=nextSequenceOfJurnalId;
		this.kodeTransaksi=transactionCode;
		this.tglTransaksi=tglTransaksi;
		this.tglPosting=tglPosting;
	}



	@Id
	@Column(name = "jurnal_id", nullable = false)
	public long getJurnalId() {
		return this.jurnalId;
	}

	public void setJurnalId(long jurnalId) {
		this.jurnalId = jurnalId;
	}

	@Column(name = "kode_transaksi", length = 5)
	public String getKodeTransaksi() {
		return this.kodeTransaksi;
	}

	public void setKodeTransaksi(String kodeTransaksi) {
		this.kodeTransaksi = kodeTransaksi;
	}

	@Column(name = "keterangan", length = 200)
	public String getKeterangan() {
		return this.keterangan;
	}

	public void setKeterangan(String keterangan) {
		this.keterangan = keterangan;
	}

	@Column(name = "is_authorized", length = 1)
	public String getAuthorized() {
		return this.authorized;
	}

	public void setAuthorized(String authorized) {
		this.authorized = authorized;
	}

	@Column(name = "authorized_by", length = 10)
	public String getAuthorizedBy() {
		return this.authorizedBy;
	}

	public void setAuthorizedBy(String authorizedBy) {
		this.authorizedBy = authorizedBy;
	}

//	@Column(name = "create_by", length = 10)
//	public String getCreateBy() {
//		return this.createBy;
//	}
//
//	public void setCreateBy(String createBy) {
//		this.createBy = createBy;
//	}

	@Column(name = "branch_code", length = 5)
	public String getBranchCode() {
		return this.branchCode;
	}

	public void setBranchCode(String branchCode) {
		this.branchCode = branchCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "authorized_date", length = 29)
	public Date getAuthorizedDate() {
		return this.authorizedDate;
	}

	public void setAuthorizedDate(Date authorizedDate) {
		this.authorizedDate = authorizedDate;
	}

	@Column(name = "ref_id", length = 30)
	public String getRefId() {
		return this.refId;
	}

	public void setRefId(String refId) {
		this.refId = refId;
	}

	@Column(name = "is_reverse", length = 1)
	public String getReverse() {
		return this.reverse;
	}

	public void setReverse(String reverse) {
		this.reverse = reverse;
	}

	@Column(name = "resp_code", length = 10)
	public String getRespCode() {
		return this.respCode;
	}

	public void setRespCode(String respCode) {
		this.respCode = respCode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "tgl_transaksi", length = 13)
	public Date getTglTransaksi() {
		return this.tglTransaksi;
	}

	public void setTglTransaksi(Date tglTransaksi) {
		this.tglTransaksi = tglTransaksi;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "tgl_posting", length = 13)
	public Date getTglPosting() {
		return this.tglPosting;
	}

	public void setTglPosting(Date tglPosting) {
		this.tglPosting = tglPosting;
	}

//	@Temporal(TemporalType.TIMESTAMP)
//	@Column(name = "create_date", length = 29)
//	public Date getCreateDate() {
//		return this.createDate;
//	}
//
//	public void setCreateDate(Date createDate) {
//		this.createDate = createDate;
//	}
//	
	@Column(name = "branch_mobile_id", length = 10)
	public String getMobileBranchCode() {
		return mobileBranchCode;
	}

	public void setMobileBranchCode(String mobileBranchCode) {
		this.mobileBranchCode = mobileBranchCode;
	}
	

}
