package com.id.kas.pojo;

// Generated Mar 2, 2015 11:08:12 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblKabupatenId generated by hbm2java
 */
@Embeddable
public class TblKabupatenId implements java.io.Serializable {

	private String kodeProvinsi;
	private String kodeKabupaten;

	public TblKabupatenId() {
	}

	public TblKabupatenId(String kodeProvinsi, String kodeKabupaten) {
		this.kodeProvinsi = kodeProvinsi;
		this.kodeKabupaten = kodeKabupaten;
	}

	@Column(name = "KODE_PROVINSI", nullable = false, length = 2)
	public String getKodeProvinsi() {
		return this.kodeProvinsi;
	}

	public void setKodeProvinsi(String kodeProvinsi) {
		this.kodeProvinsi = kodeProvinsi;
	}

	@Column(name = "KODE_KABUPATEN", nullable = false, length = 4)
	public String getKodeKabupaten() {
		return this.kodeKabupaten;
	}

	public void setKodeKabupaten(String kodeKabupaten) {
		this.kodeKabupaten = kodeKabupaten;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblKabupatenId))
			return false;
		TblKabupatenId castOther = (TblKabupatenId) other;

		return ((this.getKodeProvinsi() == castOther.getKodeProvinsi()) || (this
				.getKodeProvinsi() != null
				&& castOther.getKodeProvinsi() != null && this
				.getKodeProvinsi().equals(castOther.getKodeProvinsi())))
				&& ((this.getKodeKabupaten() == castOther.getKodeKabupaten()) || (this
						.getKodeKabupaten() != null
						&& castOther.getKodeKabupaten() != null && this
						.getKodeKabupaten()
						.equals(castOther.getKodeKabupaten())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getKodeProvinsi() == null ? 0 : this.getKodeProvinsi()
						.hashCode());
		result = 37
				* result
				+ (getKodeKabupaten() == null ? 0 : this.getKodeKabupaten()
						.hashCode());
		return result;
	}

}
