package com.id.kas.pojo;

// Generated Mar 2, 2015 11:08:12 AM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblKabupaten generated by hbm2java
 */
@Entity
@Table(name = "TBL_KABUPATEN", schema = "TESTDB")
public class TblKabupaten implements java.io.Serializable {
	private String kodeProvinsi;
	private String kodeKabupaten;
//	private TblKabupatenId id;
	private String createBy;
	private Date createDate;
	private String updateBy;
	private Date updateDate;
	private BigDecimal versi;
	private String namaKabupaten;
	
	@Id
	@Column(name = "KODE_PROVINSI", nullable = false, length = 2)
	public String getKodeProvinsi() {
		return this.kodeProvinsi;
	}

	public void setKodeProvinsi(String kodeProvinsi) {
		this.kodeProvinsi = kodeProvinsi;
	}
	@Id
	@Column(name = "KODE_KABUPATEN", nullable = false, length = 4)
	public String getKodeKabupaten() {
		return this.kodeKabupaten;
	}

	public void setKodeKabupaten(String kodeKabupaten) {
		this.kodeKabupaten = kodeKabupaten;
	}

	
	
	

//	public TblKabupaten() {
//	}

//	public TblKabupaten(TblKabupatenId id, String namaKabupaten) {
//		this.id = id;
//		this.namaKabupaten = namaKabupaten;
//	}

//	public TblKabupaten(TblKabupatenId id, String createBy, Date createDate,
//			String updateBy, Date updateDate, BigDecimal versi,
//			String namaKabupaten) {
//		this.id = id;
//		this.createBy = createBy;
//		this.createDate = createDate;
//		this.updateBy = updateBy;
//		this.updateDate = updateDate;
//		this.versi = versi;
//		this.namaKabupaten = namaKabupaten;
//	}

//	@EmbeddedId
//	@AttributeOverrides({
//			@AttributeOverride(name = "kodeProvinsi", column = @Column(name = "KODE_PROVINSI", nullable = false, length = 2)),
//			@AttributeOverride(name = "kodeKabupaten", column = @Column(name = "KODE_KABUPATEN", nullable = false, length = 4)) })
//	public TblKabupatenId getId() {
//		return this.id;
//	}

//	public void setId(TblKabupatenId id) {
//		this.id = id;
//	}

	@Column(name = "CREATE_BY", length = 20)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATE_DATE", length = 7)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "UPDATE_BY", length = 20)
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "UPDATE_DATE", length = 7)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "VERSI", scale = 0)
	public BigDecimal getVersi() {
		return this.versi;
	}

	public void setVersi(BigDecimal versi) {
		this.versi = versi;
	}

	@Column(name = "NAMA_KABUPATEN", nullable = false, length = 200)
	public String getNamaKabupaten() {
		return this.namaKabupaten;
	}

	public void setNamaKabupaten(String namaKabupaten) {
		this.namaKabupaten = namaKabupaten;
	}

}
