package com.id.kas.pojo;

// Generated Jan 21, 2013 10:52:40 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblTeller generated by hbm2java
 */
@Entity
@Table(name = "tbl_teller", schema = "TESTDB")
public class TblKasir extends AuditTrail implements java.io.Serializable {

	private String norek;
	private String userId;
	private String branchCode;
	private String ccy;
	private BigDecimal amount;
	private String status;
	private BigDecimal limitAmount;
	private String branchMapping;
	
//	private TblUser tblUser;

	public TblKasir() {
	}

//	public TblTeller(String norek, String branchCode, String userId, String ccy, BigDecimal amount) {
	public TblKasir(String norek, String branchCode, String ccy, BigDecimal amount, String userId) {
		this.norek = norek;
		this.userId = userId;
		this.branchCode = branchCode;
		this.ccy = ccy;
		this.amount = amount;
	}

	public TblKasir(String norek, String branchCode, String ccy, BigDecimal amount, String status, BigDecimal limitAmount, String userId) {
		this.norek = norek;
		this.userId = userId;
		this.branchCode = branchCode;
		this.ccy = ccy;
		this.amount = amount;
		this.status = status;
		this.limitAmount = limitAmount;
	}

	
	@Column(name = "norek", nullable = false, length = 15)
	public String getNorek() {
		return this.norek;
	}

	public void setNorek(String norek) {
		this.norek = norek;
	}
	@Id
	@Column(name = "user_id", nullable = false, length = 10)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "branch_code", nullable = false, length = 5)
	public String getBranchCode() {
		return this.branchCode;
	}

	public void setBranchCode(String branchCode) {
		this.branchCode = branchCode;
	}

	@Column(name = "ccy", nullable = false, length = 3)
	public String getCcy() {
		return this.ccy;
	}

	public void setCcy(String ccy) {
		this.ccy = ccy;
	}

	@Column(name = "amount", nullable = false, precision = 20,scale=2)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "status", length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "limit_amount", precision = 20,scale=2)
	public BigDecimal getLimitAmount() {
		return this.limitAmount;
	}

	public void setLimitAmount(BigDecimal limitAmount) {
		this.limitAmount = limitAmount;
	}
	
	@Column(name = "branch_mapping", length = 255)
	public String getBranchMapping() {
		return branchMapping;
	}

	public void setBranchMapping(String branchMapping) {
		this.branchMapping = branchMapping;
	}
	
//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "user_id", nullable = false)
//	public TblUser getTblUser() {
//		return this.tblUser;
//	}
//
//	public void setTblUser(TblUser tblUser) {
//		this.tblUser = tblUser;
//	}

}
