package com.id.kas.pojo;

// Generated Mar 2, 2015 11:08:12 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TblKecamatanId generated by hbm2java
 */
@Embeddable
public class TblKecamatanId implements java.io.Serializable {

	private String kodeKecamatan;
	private String kodeKabupaten;

	public TblKecamatanId() {
	}

	public TblKecamatanId(String kodeKecamatan, String kodeKabupaten) {
		this.kodeKecamatan = kodeKecamatan;
		this.kodeKabupaten = kodeKabupaten;
	}

	@Column(name = "KODE_KECAMATAN", nullable = false, length = 6)
	public String getKodeKecamatan() {
		return this.kodeKecamatan;
	}

	public void setKodeKecamatan(String kodeKecamatan) {
		this.kodeKecamatan = kodeKecamatan;
	}

	@Column(name = "KODE_KABUPATEN", nullable = false, length = 4)
	public String getKodeKabupaten() {
		return this.kodeKabupaten;
	}

	public void setKodeKabupaten(String kodeKabupaten) {
		this.kodeKabupaten = kodeKabupaten;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblKecamatanId))
			return false;
		TblKecamatanId castOther = (TblKecamatanId) other;

		return ((this.getKodeKecamatan() == castOther.getKodeKecamatan()) || (this
				.getKodeKecamatan() != null
				&& castOther.getKodeKecamatan() != null && this
				.getKodeKecamatan().equals(castOther.getKodeKecamatan())))
				&& ((this.getKodeKabupaten() == castOther.getKodeKabupaten()) || (this
						.getKodeKabupaten() != null
						&& castOther.getKodeKabupaten() != null && this
						.getKodeKabupaten()
						.equals(castOther.getKodeKabupaten())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getKodeKecamatan() == null ? 0 : this.getKodeKecamatan()
						.hashCode());
		result = 37
				* result
				+ (getKodeKabupaten() == null ? 0 : this.getKodeKabupaten()
						.hashCode());
		return result;
	}

}
