package com.id.kas.pojo;

// Generated Mar 2, 2015 11:08:12 AM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblPwdChgHist generated by hbm2java
 */
@Entity
@Table(name = "TBL_PWD_CHG_HIST", schema = "TESTDB")
public class TblPwdChgHist implements java.io.Serializable {

	private BigDecimal id;
	private String changeBy;
	private Date changeTime;
	private String description;
	private String oldPwd;
	private String userId;

	public TblPwdChgHist() {
	}

	public TblPwdChgHist(BigDecimal id, String userId) {
		this.id = id;
		this.userId = userId;
	}

	public TblPwdChgHist(BigDecimal id, String changeBy, Date changeTime,
			String description, String oldPwd, String userId) {
		this.id = id;
		this.changeBy = changeBy;
		this.changeTime = changeTime;
		this.description = description;
		this.oldPwd = oldPwd;
		this.userId = userId;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "CHANGE_BY", length = 10)
	public String getChangeBy() {
		return this.changeBy;
	}

	public void setChangeBy(String changeBy) {
		this.changeBy = changeBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CHANGE_TIME", length = 7)
	public Date getChangeTime() {
		return this.changeTime;
	}

	public void setChangeTime(Date changeTime) {
		this.changeTime = changeTime;
	}

	@Column(name = "DESCRIPTION", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "OLD_PWD", length = 200)
	public String getOldPwd() {
		return this.oldPwd;
	}

	public void setOldPwd(String oldPwd) {
		this.oldPwd = oldPwd;
	}

	@Column(name = "USER_ID", nullable = false, length = 10)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

}
