package com.id.kas.pojo;

// Generated Jan 21, 2013 10:52:40 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblIa generated by hbm2java
 */
@Entity
@Table(name = "tbl_ia", schema = "TESTDB")
public class TblRekeningIA implements java.io.Serializable {

	private String norek;
	private String noCOA;
	private String norekIAMaster;
	private String description;
	private Date tglBuka;
	private BigDecimal saldoAwal;
	private BigDecimal saldoAkhir;
	private BigDecimal mutasiD;
	private BigDecimal mutasiK;
	private String branchCode;
	private String saldoNormal;
	private Date lastTrxDate;
	private String alternateId;
	private String createBy;
	
	public TblRekeningIA() {
	}

	public TblRekeningIA(String norek, String noCOA, String norekIAMaster, BigDecimal saldoAwal, BigDecimal saldoAkhir, BigDecimal mutasiD, BigDecimal mutasiK) {
		this.norek = norek;
		this.noCOA = noCOA;
		this.norekIAMaster = norekIAMaster;
		this.saldoAwal = saldoAwal;
		this.saldoAkhir = saldoAkhir;
		this.mutasiD = mutasiD;
		this.mutasiK = mutasiK;
	}

	public TblRekeningIA(String norek, String noCOA, String norekIAMaster, String description, Date tglBuka, BigDecimal saldoAwal, BigDecimal saldoAkhir, BigDecimal mutasiD, BigDecimal mutasiK, String branchCode, String saldoNormal, Date lastTrxDate, String createBy) {
		this.norek = norek;
		this.noCOA = noCOA;
		this.norekIAMaster = norekIAMaster;
		this.description = description;
		this.tglBuka = tglBuka;
		this.saldoAwal = saldoAwal;
		this.saldoAkhir = saldoAkhir;
		this.mutasiD = mutasiD;
		this.mutasiK = mutasiK;
		this.branchCode = branchCode;
		this.saldoNormal = saldoNormal;
		this.lastTrxDate = lastTrxDate;
		this.createBy = createBy;
	}

	@Id
	@Column(name = "no_rek", nullable = false, length = 15)
	public String getNorek() {
		return this.norek;
	}

	public void setNorek(String norek) {
		this.norek = norek;
	}

	@Column(name = "no_coa", nullable = false, length = 13)
	public String getNoCOA() {
		return this.noCOA;
	}

	public void setNoCOA(String noCOA) {
		this.noCOA = noCOA;
	}

	@Column(name = "no_rek_ia_master", nullable = false, length = 7)
	public String getNorekIAMaster() {
		return this.norekIAMaster;
	}

	public void setNorekIAMaster(String norekIAMaster) {
		this.norekIAMaster = norekIAMaster;
	}

	@Column(name = "description", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "tgl_buka", length = 13)
	public Date getTglBuka() {
		return this.tglBuka;
	}

	public void setTglBuka(Date tglBuka) {
		this.tglBuka = tglBuka;
	}

	@Column(name = "saldo_awal", nullable = false, precision = 20,scale=2)
	public BigDecimal getSaldoAwal() {
		return this.saldoAwal;
	}

	public void setSaldoAwal(BigDecimal saldoAwal) {
		this.saldoAwal = saldoAwal;
	}

	@Column(name = "saldo_akhir", nullable = false, precision = 20,scale=2)
	public BigDecimal getSaldoAkhir() {
		return this.saldoAkhir;
	}

	public void setSaldoAkhir(BigDecimal saldoAkhir) {
		this.saldoAkhir = saldoAkhir;
	}

	@Column(name = "mutasi_d", nullable = false, precision = 20,scale=2)
	public BigDecimal getMutasiD() {
		return this.mutasiD;
	}

	public void setMutasiD(BigDecimal mutasiD) {
		this.mutasiD = mutasiD;
	}

	@Column(name = "mutasi_k", nullable = false, precision = 20,scale=2)
	public BigDecimal getMutasiK() {
		return this.mutasiK;
	}

	public void setMutasiK(BigDecimal mutasiK) {
		this.mutasiK = mutasiK;
	}

	@Column(name = "branch_code", length = 5)
	public String getBranchCode() {
		return this.branchCode;
	}

	public void setBranchCode(String branchCode) {
		this.branchCode = branchCode;
	}

	@Column(name = "saldo_normal", length = 1)
	public String getSaldoNormal() {
		return this.saldoNormal;
	}

	public void setSaldoNormal(String saldoNormal) {
		this.saldoNormal = saldoNormal;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "last_trx_date", length = 13)
	public Date getLastTrxDate() {
		return this.lastTrxDate;
	}

	public void setLastTrxDate(Date lastTrxDate) {
		this.lastTrxDate = lastTrxDate;
	}

	@Column(name = "alternate_id", length = 20)
	public String getAlternateId() {
		return alternateId;
	}

	public void setAlternateId(String alternateId) {
		this.alternateId = alternateId;
	}
	
	@Column(name = "create_by", length = 20)
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}
}
