package com.id.kas.pojo;

// Generated Mar 2, 2015 11:08:12 AM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.envers.Audited;
/**
 * TblSeq generated by hbm2java
 */
@Entity
@Audited
@Table(name = "TBL_SEQ", schema = "TESTDB")
public class TblSeq extends AuditTrail implements java.io.Serializable {

	private String seqName;
	private long seqNum;
	private String keterangan;
	private Date lastLogIn;
	private BigDecimal tarif;
	@Column(name = "KETERANGAN", unique = false, nullable = false, length = 100)
	public String getKeterangan() {
		return keterangan;
	}

	public void setKeterangan(String keterangan) {
		this.keterangan = keterangan;
	}

	public TblSeq() {
	}

	public TblSeq(String seqName, long seqNum) {
		this.seqName = seqName;
		this.seqNum = seqNum;
	}

	@Id
	@Column(name = "SEQ_NAME", unique = true, nullable = false, length = 100)
	public String getSeqName() {
		return this.seqName;
	}

	public void setSeqName(String seqName) {
		this.seqName = seqName;
	}

	@Column(name = "SEQ_NUM", nullable = false, precision = 10, scale = 0)
	public long getSeqNum() {
		return this.seqNum;
	}

	public void setSeqNum(long seqNum) {
		this.seqNum = seqNum;
	}

	@Column(name = "TARIF", unique = false, nullable = false, length = 8, scale = 0)
	public BigDecimal getTarif() {
		return this.tarif;
	}

	public void setTarif(BigDecimal tarif) {
		this.tarif = tarif;
	}
	
	
	

	@Temporal(TemporalType.DATE)
	@Column(name = "LAST_LOG_IN", length = 7)
	public Date getLastLogIn() {
		return this.lastLogIn;
	}

	public void setLastLogIn(Date lastLogIn) {
		this.lastLogIn = lastLogIn;
	}
	
}
